version: '3.8'

services:
  s3proxy:
    build:
      context: ./s3proxy
      dockerfile: Dockerfile
    container_name: bazel-s3-proxy
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-default}
      - AWS_REGION=${AWS_REGION:-sa-east-1}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - "${PROXY_PORT:-8888}:8888"
    volumes:
      - ${HOME}/.aws:/root/.aws:ro
      - maven-cache:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  credential-monitor:
    build:
      context: ./credential-monitor
      dockerfile: Dockerfile
    container_name: aws-credential-monitor
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-default}
      - REFRESH_INTERVAL=${REFRESH_INTERVAL:-60000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ${HOME}/.aws:/root/.aws:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    depends_on:
      - s3proxy

volumes:
  maven-cache:
    name: bazel-aws-maven-proxy_maven-cache
